available_text_models: ["davinci:ft-dales-project-2023-04-15-17-53-10", "gpt-3.5-turbo"]

info:
  gpt-3.5-turbo:
    type: chat_completion
    name: ChatGPT
    description: ChatGPT is that well-known model. It's <b>fast</b> and <b>cheap</b>. Ideal for everyday tasks. If there are some tasks it can't handle, try the <b>GPT-4</b>.

    price_per_1000_input_tokens: 0.002
    price_per_1000_output_tokens: 0.002

    scores:
      Smart: 3
      Fast: 5
      Cheap: 5

  davinci:ft-dales-project-2023-04-15-17-53-10:
    type: completion
    name: Fine Tuned Davinci
    description: This is a fine tuned variant of davinci which is the most capable GPT-3 model. Can do any task the other models can do, often with higher quality.

    price_per_1000_input_tokens: 0.02
    price_per_1000_output_tokens: 0.02

    scores:
      Smart: 3
      Fast: 2
      Cheap: 3

  whisper:
    type: audio
    price_per_1_min: 0.006